name: 'Open Multiple Pull Requests'
description: 'Specify a matching regex pattern to search for branches to merge changes into'
inputs:
  main_branch:
    description: 'Main branch name'
    required: true
  source_regex:
    description: 'Source branch regex to match'
    required: true
  destination_regex:
    description: 'Destination branch regex to match'
    required: true
  pr_allow_empty:
    description: 'Allows an empty PR to be merged'
    required: false
  github_token:
    description: 'The github access token to use gh api commands'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.main_branch }}
    - ${{ inputs.source_regex }}
    - ${{ inputs.destination_regex }}
    - ${{ inputs.pr_allow_empty }}
    - ${{ inputs.github_token }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
