name: 'Open Multiple Pull Requests'
description: 'Specify a matching regex pattern to search for branches to merge changes into'
inputs:
  source-regex:
    description: 'Source branch regex to match'
    required: true
  destination-regex:
    description: 'Destination branch regex to match'
    required: true
  github-token:
    description: 'The github access token to use gh api commands'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-regex }}
    - ${{ inputs.destination-regex }}
    - ${{ inputs.github-token }}
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
