name: 'Open Multiple Pull Requests'
description: 'Specify a matching regex pattern to search for branches to merge changes into'
inputs:
  source_regex:
    description: 'Source branch regex to match'
    required: true
  destination_regex:
    description: 'Destination branch regex to match'
    required: true
  github_token:
    description: 'The github access token to use gh api commands'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source_regex }}
    - ${{ inputs.destination_regex }}
    - ${{ inputs.github_token }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
